#!/bin/bash
set -e

echo "Terraform action selected: $TF_ACTION"
echo "Workspace: $(pwd)"

terraform --version

echo "Initializing Terraform..."
terraform init

echo "Running Terraform Plan..."
terraform plan

if [ "$TF_ACTION" = "apply" ]; then
    echo "Applying Terraform..."
    terraform apply -auto-approve
elif [ "$TF_ACTION" = "destroy" ]; then
    echo "Destroying Terraform resources..."
    terraform destroy -auto-approve
else
    echo "Invalid Terraform action"
    exit 1
fi
